### ISSUE TITLE
Design a Logo for Ribbon Stitchery

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/ribbon-stichery#1]
Ribbon Stitchery's current website address (not published): http://34.226.30.20

Their current logo is on the top left corner of their website. It is way too small and it's not very good. Design a new logo for them. Be creative.

Create your design on Figma and submit the link to the Figma file here.

Due Date: Sunday, 5/3/2020

**Comment by WilliamShih1234** [comment]
https://www.figma.com/file/JiGW6oYYGLZjhQ2P4N3iOx/Untitled?node-id=0%3A1
