### ISSUE TITLE
Design a New Homepage "Ribbon Stitchery Community" Section Header Image

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/ribbon-stichery#2]
Ribbon Stitchery's current website address (not published): http://34.226.30.20

The current image under the "Ribbon Stitchery Community" Section in the homepage is not very good. Design a new one that conveys a similar message (stores spreads across the U.S.)

Create your design on Figma and submit the link to the Figma file here.

Due Date: Sunday, 5/3/2020

**Comment by WilliamShih1234** [comment]
https://www.figma.com/file/mUjaJCzCM4RLj94aRdQUww/Locations-Picture?node-id=0%3A1
